image: "$REGISTRY/openshift/cli:latest"

stages:
  - build
  - docker_build
  - deploy
  - clean

cache:
  paths:
    - $APP_NAME/.gradle/wrapper
    - $APP_NAME/.gradle/caches

build:
  image: bellsoft/liberica-openjdk-alpine:11.0.11
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/$APP_NAME/.gradle
  script:
    - chmod +x ./$APP_NAME/gradlew
    - cd $APP_NAME && ./gradlew assemble
  artifacts:
    paths:
      - $APP_NAME/build/libs/*.jar
    expire_in: 1 day
  only:
    - stage
  tags:
    - java_school

docker_build:
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: 'builder'
  stage: docker_build
  image:
    name: $REGISTRY/openshift/kaniko:openshift
  script:
    - cat /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt >> $SSL_CERT_DIR/ca-certificates.crt
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"serviceaccount\",\"password\":\"$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"}}}" > $DOCKER_CONFIG/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/$APP_NAME --dockerfile $CI_PROJECT_DIR/$APP_NAME/Dockerfile --destination $APP_IMAGE:$TEMP_IMAGE_TAG --cache=true --cache-repo ${APP_IMAGE}-cache
  only:
    - stage
  tags:
    - java_school

deploy_staging:
  stage: deploy
  script:
    - oc tag $NAMESPACE/$APP_NAME:$TEMP_IMAGE_TAG $NAMESPACE/$APP_NAME:latest
  only:
    - stage
  tags:
    - java_school

clean:
  stage: clean
  script:
    - oc delete istag/$APP_NAME:$TEMP_IMAGE_TAG -n $NAMESPACE
  tags:
    - java_school
  only:
    - stage
  when: always
