version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    restart: on-failure:1
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - sso-net

  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - sso-net

  keycloak:
    image: 'jboss/keycloak'
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak-server:/tmp
    ports:
      - 8180:8443
    depends_on:
      - db
    networks:
      - sso-net

networks:
  sso-net:
    name: sso-net
    driver: bridge