eureka:
  instance:
    hostname: eureka-server-java-school.apps.okd.stage.digital.rt.ru
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sso_resource
    username: # set value
    password: # set value
    driver-class-name: org.postgresql.Driver