server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  # added
  instance:
    hostname: ${DOCKER_HOST:localhost}
  #
  client:
    register-with-eureka: false
    fetch-registry: false